### ISSUE TITLE
I want to add insertion sort code in C pls assign me 

### ISSUE THREAD

**Issue by piyushkandari** [URVESH1121/DSA-and-Programming#6]

**Comment by URVESH1121** [comment]
now you can add it

**Comment by piyushkandari** [comment]
![insertionsort](https://user-images.githubusercontent.com/103874608/194747764-fce3b4f2-44ea-4765-9262-caf0cebad903.png)

**Comment by URVESH1121** [comment]
you have to create a file in the repo and then create PR.

**Comment by URVESH1121** [comment]
Done
